name: Dependabot CI Updates

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

permissions:
  contents: read

jobs:
  dependabot-auto-approve:
    name: Auto-approve and auto-merge safe Dependabot updates
    runs-on: ubuntu-latest
    environment: automation
    if: >
      github.event.pull_request.user.login == 'dependabot[bot]' &&
      contains(github.event.pull_request.labels.*.name, 'dependencies')
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Generate GitHub App token
        id: token_generator
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        with:
          app-id: ${{ secrets.HYDROLOGIE_HELPER_BOT_ID }}
          private-key: ${{ secrets.HYDROLOGIE_HELPER_BOT_KEY }}

      - name: Fetch Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@ffa630c65fa7e0ecfa0625b5ceda64399aea1b36 # v3.0.0
        with:
          github-token: ${{ steps.token_generator.outputs.token }}

      - name: Stop workflow if not minor update or patch update
        id: skip-condition
        if: >
          steps.dependabot-metadata.outputs.update-type != 'version-update:semver-minor' &&
          steps.dependabot-metadata.outputs.update-type != 'version-update:semver-patch'
        run: |
          echo "Not a minor or patch update; skipping auto-approval."
          echo "skip=true" >> $GITHUB_OUTPUT

      - name: Checkout Repository
        if: steps.skip-condition.outputs.skip != 'true'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.token_generator.outputs.token }}
          persist-credentials: false

      - name: Approve Changes
        if: steps.skip-condition.outputs.skip != 'true'
        run: |
          decision="$(gh pr status --json reviewDecision -q .currentBranch.reviewDecision)"
          if [ "$decision" != "APPROVED" ]; then
            gh pr review --approve "$PR_URL"
          else
            echo "PR already approved: skipping approval."
          fi
        env:
          GH_TOKEN: ${{ steps.token_generator.outputs.token }}
          PR_URL: ${{ github.event.pull_request.html_url }}

      - name: Enable auto-merge on Pull Request
        if: steps.skip-condition.outputs.skip != 'true'
        run: |
          gh pr merge --auto --merge "$PR_URL"
        env:
          GH_TOKEN: ${{ steps.token_generator.outputs.token }}
          PR_URL: ${{ github.event.pull_request.html_url }}
