name: Label Pull Request on Pull Request review approval

on:
  pull_request_review:
    types:
      - submitted
  pull_request_target:
    types:
      - ready_for_review
      - review_requested

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  label_approved:
    name: Label on Approval
    if: |
      (!contains(github.event.pull_request.labels.*.name, 'approved')) &&
      (github.event.review.state == 'approved') &&
      (github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name)
    runs-on: ubuntu-latest
    steps:
      - name: Label Approved
        uses: actions/github-script@v7.0.1
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['approved']
            })

  comment_approved:
    name: Comment Concerning Approved Tag
    if: |
      (github.event_name == 'pull_request_target') &&
      (github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name)
    runs-on: ubuntu-latest
    steps:
      - name: Find comment
        uses: peter-evans/find-comment@v2.4.0
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: This Pull Request is coming from a fork and must be manually tagged `approved` in order to perform additional testing
      - name: Create comment
        if: |
          (steps.fc.outputs.comment-id == '') &&
          (!contains(github.event.pull_request.labels.*.name, 'approved')) &&
          (github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name)
        uses: peter-evans/create-or-update-comment@v3.1.0
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            > **Warning**
            > This Pull Request is coming from a fork and must be manually tagged `approved` in order to perform additional testing.
          edit-mode: replace
      - name: Update comment
        if: |
          contains(github.event.pull_request.labels.*.name, 'approved')
        uses: peter-evans/create-or-update-comment@v3.1.0
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            > **Note**
            > This Pull Request is approved!
          reactions: |
            hooray
          edit-mode: append
